// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DelegatesList delegates list
//
// swagger:model DelegatesList
type DelegatesList []string

// Validate validates this delegates list
func (m DelegatesList) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delegates list based on context it is used
func (m DelegatesList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
