// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// EncodedByteArray Base64Check encoded tagged byte array
// swagger:model EncodedByteArray
type EncodedByteArray string

// Validate validates this encoded byte array
func (m EncodedByteArray) Validate(formats strfmt.Registry) error {
	return nil
}
