// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// EncodedPubkey Base58Check encoded tagged pubkey
// swagger:model EncodedPubkey
type EncodedPubkey string

// Validate validates this encoded pubkey
func (m EncodedPubkey) Validate(formats strfmt.Registry) error {
	return nil
}
