// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// EncodedHash Base58Check encoded tagged hash
//
// swagger:model EncodedHash
type EncodedHash string

// Validate validates this encoded hash
func (m EncodedHash) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this encoded hash based on context it is used
func (m EncodedHash) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
