// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostTxResponse post tx response
// swagger:model PostTxResponse
type PostTxResponse struct {

	// Hash of a signed transaction
	// Required: true
	TxHash *string `json:"tx_hash"`
}

// Validate validates this post tx response
func (m *PostTxResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTxHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostTxResponse) validateTxHash(formats strfmt.Registry) error {

	if err := validate.Required("tx_hash", "body", m.TxHash); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostTxResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTxResponse) UnmarshalBinary(b []byte) error {
	var res PostTxResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
