// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TTL TTL
//
// swagger:model TTL
type TTL struct {

	// type
	// Required: true
	// Enum: [delta block]
	Type *string `json:"type"`

	// value
	// Required: true
	Value *uint64 `json:"value"`
}

// Validate validates this TTL
func (m *TTL) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var ttlTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["delta","block"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ttlTypeTypePropEnum = append(ttlTypeTypePropEnum, v)
	}
}

const (

	// TTLTypeDelta captures enum value "delta"
	TTLTypeDelta string = "delta"

	// TTLTypeBlock captures enum value "block"
	TTLTypeBlock string = "block"
)

// prop value enum
func (m *TTL) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, ttlTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TTL) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

func (m *TTL) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this TTL based on context it is used
func (m *TTL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TTL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TTL) UnmarshalBinary(b []byte) error {
	var res TTL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
