// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aeternity/aepp-sdk-go/v9/swagguard/compiler/models"
)

// CompileContractReader is a Reader for the CompileContract structure.
type CompileContractReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompileContractReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompileContractOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCompileContractBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCompileContractOK creates a CompileContractOK with default headers values
func NewCompileContractOK() *CompileContractOK {
	return &CompileContractOK{}
}

/* CompileContractOK describes a response with status code 200, with default header values.

Byte code response
*/
type CompileContractOK struct {
	Payload *models.ByteCode
}

func (o *CompileContractOK) Error() string {
	return fmt.Sprintf("[POST /compile][%d] compileContractOK  %+v", 200, o.Payload)
}
func (o *CompileContractOK) GetPayload() *models.ByteCode {
	return o.Payload
}

func (o *CompileContractOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ByteCode)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompileContractBadRequest creates a CompileContractBadRequest with default headers values
func NewCompileContractBadRequest() *CompileContractBadRequest {
	return &CompileContractBadRequest{}
}

/* CompileContractBadRequest describes a response with status code 400, with default header values.

Invalid contract
*/
type CompileContractBadRequest struct {
	Payload models.CompilerErrors
}

func (o *CompileContractBadRequest) Error() string {
	return fmt.Sprintf("[POST /compile][%d] compileContractBadRequest  %+v", 400, o.Payload)
}
func (o *CompileContractBadRequest) GetPayload() models.CompilerErrors {
	return o.Payload
}

func (o *CompileContractBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
