// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aeternity/aepp-sdk-go/v8/swagguard/compiler/models"
)

// NewCompileContractParams creates a new CompileContractParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCompileContractParams() *CompileContractParams {
	return &CompileContractParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCompileContractParamsWithTimeout creates a new CompileContractParams object
// with the ability to set a timeout on a request.
func NewCompileContractParamsWithTimeout(timeout time.Duration) *CompileContractParams {
	return &CompileContractParams{
		timeout: timeout,
	}
}

// NewCompileContractParamsWithContext creates a new CompileContractParams object
// with the ability to set a context for a request.
func NewCompileContractParamsWithContext(ctx context.Context) *CompileContractParams {
	return &CompileContractParams{
		Context: ctx,
	}
}

// NewCompileContractParamsWithHTTPClient creates a new CompileContractParams object
// with the ability to set a custom HTTPClient for a request.
func NewCompileContractParamsWithHTTPClient(client *http.Client) *CompileContractParams {
	return &CompileContractParams{
		HTTPClient: client,
	}
}

/* CompileContractParams contains all the parameters to send to the API endpoint
   for the compile contract operation.

   Typically these are written to a http.Request.
*/
type CompileContractParams struct {

	/* Body.

	   contract code
	*/
	Body *models.Contract

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the compile contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompileContractParams) WithDefaults() *CompileContractParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the compile contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompileContractParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the compile contract params
func (o *CompileContractParams) WithTimeout(timeout time.Duration) *CompileContractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the compile contract params
func (o *CompileContractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the compile contract params
func (o *CompileContractParams) WithContext(ctx context.Context) *CompileContractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the compile contract params
func (o *CompileContractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the compile contract params
func (o *CompileContractParams) WithHTTPClient(client *http.Client) *CompileContractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the compile contract params
func (o *CompileContractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the compile contract params
func (o *CompileContractParams) WithBody(body *models.Contract) *CompileContractParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the compile contract params
func (o *CompileContractParams) SetBody(body *models.Contract) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CompileContractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
