// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/v5/swagguard/compiler/models"
)

// NewDecodeCalldataBytecodeParams creates a new DecodeCalldataBytecodeParams object
// with the default values initialized.
func NewDecodeCalldataBytecodeParams() *DecodeCalldataBytecodeParams {
	var ()
	return &DecodeCalldataBytecodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDecodeCalldataBytecodeParamsWithTimeout creates a new DecodeCalldataBytecodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDecodeCalldataBytecodeParamsWithTimeout(timeout time.Duration) *DecodeCalldataBytecodeParams {
	var ()
	return &DecodeCalldataBytecodeParams{

		timeout: timeout,
	}
}

// NewDecodeCalldataBytecodeParamsWithContext creates a new DecodeCalldataBytecodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDecodeCalldataBytecodeParamsWithContext(ctx context.Context) *DecodeCalldataBytecodeParams {
	var ()
	return &DecodeCalldataBytecodeParams{

		Context: ctx,
	}
}

// NewDecodeCalldataBytecodeParamsWithHTTPClient creates a new DecodeCalldataBytecodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDecodeCalldataBytecodeParamsWithHTTPClient(client *http.Client) *DecodeCalldataBytecodeParams {
	var ()
	return &DecodeCalldataBytecodeParams{
		HTTPClient: client,
	}
}

/*DecodeCalldataBytecodeParams contains all the parameters to send to the API endpoint
for the decode calldata bytecode operation typically these are written to a http.Request
*/
type DecodeCalldataBytecodeParams struct {

	/*Body
	  Calldata + compiled contract

	*/
	Body *models.DecodeCalldataBytecode

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) WithTimeout(timeout time.Duration) *DecodeCalldataBytecodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) WithContext(ctx context.Context) *DecodeCalldataBytecodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) WithHTTPClient(client *http.Client) *DecodeCalldataBytecodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) WithBody(body *models.DecodeCalldataBytecode) *DecodeCalldataBytecodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the decode calldata bytecode params
func (o *DecodeCalldataBytecodeParams) SetBody(body *models.DecodeCalldataBytecode) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DecodeCalldataBytecodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
