// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aeternity/aepp-sdk-go/v9/swagguard/compiler/models"
)

// NewGetFateAssemblerCodeParams creates a new GetFateAssemblerCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFateAssemblerCodeParams() *GetFateAssemblerCodeParams {
	return &GetFateAssemblerCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFateAssemblerCodeParamsWithTimeout creates a new GetFateAssemblerCodeParams object
// with the ability to set a timeout on a request.
func NewGetFateAssemblerCodeParamsWithTimeout(timeout time.Duration) *GetFateAssemblerCodeParams {
	return &GetFateAssemblerCodeParams{
		timeout: timeout,
	}
}

// NewGetFateAssemblerCodeParamsWithContext creates a new GetFateAssemblerCodeParams object
// with the ability to set a context for a request.
func NewGetFateAssemblerCodeParamsWithContext(ctx context.Context) *GetFateAssemblerCodeParams {
	return &GetFateAssemblerCodeParams{
		Context: ctx,
	}
}

// NewGetFateAssemblerCodeParamsWithHTTPClient creates a new GetFateAssemblerCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFateAssemblerCodeParamsWithHTTPClient(client *http.Client) *GetFateAssemblerCodeParams {
	return &GetFateAssemblerCodeParams{
		HTTPClient: client,
	}
}

/* GetFateAssemblerCodeParams contains all the parameters to send to the API endpoint
   for the get fate assembler code operation.

   Typically these are written to a http.Request.
*/
type GetFateAssemblerCodeParams struct {

	/* Body.

	   contract byte array
	*/
	Body *models.ByteCodeInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fate assembler code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFateAssemblerCodeParams) WithDefaults() *GetFateAssemblerCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fate assembler code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFateAssemblerCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) WithTimeout(timeout time.Duration) *GetFateAssemblerCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) WithContext(ctx context.Context) *GetFateAssemblerCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) WithHTTPClient(client *http.Client) *GetFateAssemblerCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) WithBody(body *models.ByteCodeInput) *GetFateAssemblerCodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get fate assembler code params
func (o *GetFateAssemblerCodeParams) SetBody(body *models.ByteCodeInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetFateAssemblerCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
