// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aeternity/aepp-sdk-go/v8/swagguard/compiler/models"
)

// GetCompilerVersionReader is a Reader for the GetCompilerVersion structure.
type GetCompilerVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCompilerVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCompilerVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCompilerVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCompilerVersionOK creates a GetCompilerVersionOK with default headers values
func NewGetCompilerVersionOK() *GetCompilerVersionOK {
	return &GetCompilerVersionOK{}
}

/* GetCompilerVersionOK describes a response with status code 200, with default header values.

The compiler version
*/
type GetCompilerVersionOK struct {
	Payload *models.CompilerVersion
}

func (o *GetCompilerVersionOK) Error() string {
	return fmt.Sprintf("[POST /compiler-version][%d] getCompilerVersionOK  %+v", 200, o.Payload)
}
func (o *GetCompilerVersionOK) GetPayload() *models.CompilerVersion {
	return o.Payload
}

func (o *GetCompilerVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CompilerVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCompilerVersionBadRequest creates a GetCompilerVersionBadRequest with default headers values
func NewGetCompilerVersionBadRequest() *GetCompilerVersionBadRequest {
	return &GetCompilerVersionBadRequest{}
}

/* GetCompilerVersionBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type GetCompilerVersionBadRequest struct {
	Payload *models.Error
}

func (o *GetCompilerVersionBadRequest) Error() string {
	return fmt.Sprintf("[POST /compiler-version][%d] getCompilerVersionBadRequest  %+v", 400, o.Payload)
}
func (o *GetCompilerVersionBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCompilerVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
