// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aeternity/aepp-sdk-go/v8/swagguard/compiler/models"
)

// NewValidateByteCodeParams creates a new ValidateByteCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateByteCodeParams() *ValidateByteCodeParams {
	return &ValidateByteCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateByteCodeParamsWithTimeout creates a new ValidateByteCodeParams object
// with the ability to set a timeout on a request.
func NewValidateByteCodeParamsWithTimeout(timeout time.Duration) *ValidateByteCodeParams {
	return &ValidateByteCodeParams{
		timeout: timeout,
	}
}

// NewValidateByteCodeParamsWithContext creates a new ValidateByteCodeParams object
// with the ability to set a context for a request.
func NewValidateByteCodeParamsWithContext(ctx context.Context) *ValidateByteCodeParams {
	return &ValidateByteCodeParams{
		Context: ctx,
	}
}

// NewValidateByteCodeParamsWithHTTPClient creates a new ValidateByteCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateByteCodeParamsWithHTTPClient(client *http.Client) *ValidateByteCodeParams {
	return &ValidateByteCodeParams{
		HTTPClient: client,
	}
}

/* ValidateByteCodeParams contains all the parameters to send to the API endpoint
   for the validate byte code operation.

   Typically these are written to a http.Request.
*/
type ValidateByteCodeParams struct {

	/* Body.

	   contract byte array and source code
	*/
	Body *models.ValidateByteCodeInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate byte code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateByteCodeParams) WithDefaults() *ValidateByteCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate byte code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateByteCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate byte code params
func (o *ValidateByteCodeParams) WithTimeout(timeout time.Duration) *ValidateByteCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate byte code params
func (o *ValidateByteCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate byte code params
func (o *ValidateByteCodeParams) WithContext(ctx context.Context) *ValidateByteCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate byte code params
func (o *ValidateByteCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate byte code params
func (o *ValidateByteCodeParams) WithHTTPClient(client *http.Client) *ValidateByteCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate byte code params
func (o *ValidateByteCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate byte code params
func (o *ValidateByteCodeParams) WithBody(body *models.ValidateByteCodeInput) *ValidateByteCodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate byte code params
func (o *ValidateByteCodeParams) SetBody(body *models.ValidateByteCodeInput) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateByteCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
