// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIVersion API version
// swagger:model APIVersion
type APIVersion struct {

	// API compiler version
	// Required: true
	APIVersion *string `json:"api-version"`
}

// Validate validates this API version
func (m *APIVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIVersion) validateAPIVersion(formats strfmt.Registry) error {

	if err := validate.Required("api-version", "body", m.APIVersion); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIVersion) UnmarshalBinary(b []byte) error {
	var res APIVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
