// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CompileOpts compile opts
// swagger:model CompileOpts
type CompileOpts struct {

	// An explicit file system, mapping file names to file content
	FileSystem interface{} `json:"file_system,omitempty"`

	// Name of contract source file - only used in error messages
	SrcFile string `json:"src_file,omitempty"`
}

// Validate validates this compile opts
func (m *CompileOpts) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompileOpts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompileOpts) UnmarshalBinary(b []byte) error {
	var res CompileOpts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
