// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FateAssembler fate assembler
// Example: {"fate-assembler":"fate-assembler"}
//
// swagger:model FateAssembler
type FateAssembler struct {

	// Fate assembler code
	// Required: true
	FateAssembler *string `json:"fate-assembler"`
}

// Validate validates this fate assembler
func (m *FateAssembler) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFateAssembler(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FateAssembler) validateFateAssembler(formats strfmt.Registry) error {

	if err := validate.Required("fate-assembler", "body", m.FateAssembler); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this fate assembler based on context it is used
func (m *FateAssembler) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FateAssembler) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FateAssembler) UnmarshalBinary(b []byte) error {
	var res FateAssembler
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
