// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlockTxsCountByHeightParams creates a new GetBlockTxsCountByHeightParams object
// with the default values initialized.
func NewGetBlockTxsCountByHeightParams() *GetBlockTxsCountByHeightParams {
	var ()
	return &GetBlockTxsCountByHeightParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlockTxsCountByHeightParamsWithTimeout creates a new GetBlockTxsCountByHeightParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBlockTxsCountByHeightParamsWithTimeout(timeout time.Duration) *GetBlockTxsCountByHeightParams {
	var ()
	return &GetBlockTxsCountByHeightParams{

		timeout: timeout,
	}
}

// NewGetBlockTxsCountByHeightParamsWithContext creates a new GetBlockTxsCountByHeightParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBlockTxsCountByHeightParamsWithContext(ctx context.Context) *GetBlockTxsCountByHeightParams {
	var ()
	return &GetBlockTxsCountByHeightParams{

		Context: ctx,
	}
}

// NewGetBlockTxsCountByHeightParamsWithHTTPClient creates a new GetBlockTxsCountByHeightParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBlockTxsCountByHeightParamsWithHTTPClient(client *http.Client) *GetBlockTxsCountByHeightParams {
	var ()
	return &GetBlockTxsCountByHeightParams{
		HTTPClient: client,
	}
}

/*GetBlockTxsCountByHeightParams contains all the parameters to send to the API endpoint
for the get block txs count by height operation typically these are written to a http.Request
*/
type GetBlockTxsCountByHeightParams struct {

	/*ExcludeTxTypes
	  Transactions types not to show. Comma separated. If a tx type appears in both tx_types and exclude_tx_types, it is excluded.

	*/
	ExcludeTxTypes *string
	/*Height
	  Height of the block to fetch

	*/
	Height int64
	/*TxTypes
	  Transactions types to show. Comma separated

	*/
	TxTypes *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithTimeout(timeout time.Duration) *GetBlockTxsCountByHeightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithContext(ctx context.Context) *GetBlockTxsCountByHeightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithHTTPClient(client *http.Client) *GetBlockTxsCountByHeightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExcludeTxTypes adds the excludeTxTypes to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithExcludeTxTypes(excludeTxTypes *string) *GetBlockTxsCountByHeightParams {
	o.SetExcludeTxTypes(excludeTxTypes)
	return o
}

// SetExcludeTxTypes adds the excludeTxTypes to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetExcludeTxTypes(excludeTxTypes *string) {
	o.ExcludeTxTypes = excludeTxTypes
}

// WithHeight adds the height to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithHeight(height int64) *GetBlockTxsCountByHeightParams {
	o.SetHeight(height)
	return o
}

// SetHeight adds the height to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetHeight(height int64) {
	o.Height = height
}

// WithTxTypes adds the txTypes to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) WithTxTypes(txTypes *string) *GetBlockTxsCountByHeightParams {
	o.SetTxTypes(txTypes)
	return o
}

// SetTxTypes adds the txTypes to the get block txs count by height params
func (o *GetBlockTxsCountByHeightParams) SetTxTypes(txTypes *string) {
	o.TxTypes = txTypes
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlockTxsCountByHeightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExcludeTxTypes != nil {

		// query param exclude_tx_types
		var qrExcludeTxTypes string
		if o.ExcludeTxTypes != nil {
			qrExcludeTxTypes = *o.ExcludeTxTypes
		}
		qExcludeTxTypes := qrExcludeTxTypes
		if qExcludeTxTypes != "" {
			if err := r.SetQueryParam("exclude_tx_types", qExcludeTxTypes); err != nil {
				return err
			}
		}

	}

	// path param height
	if err := r.SetPathParam("height", swag.FormatInt64(o.Height)); err != nil {
		return err
	}

	if o.TxTypes != nil {

		// query param tx_types
		var qrTxTypes string
		if o.TxTypes != nil {
			qrTxTypes = *o.TxTypes
		}
		qTxTypes := qrTxTypes
		if qTxTypes != "" {
			if err := r.SetQueryParam("tx_types", qTxTypes); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
