// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMicroBlockTransactionsCountByHashParams creates a new GetMicroBlockTransactionsCountByHashParams object
// with the default values initialized.
func NewGetMicroBlockTransactionsCountByHashParams() *GetMicroBlockTransactionsCountByHashParams {
	var ()
	return &GetMicroBlockTransactionsCountByHashParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMicroBlockTransactionsCountByHashParamsWithTimeout creates a new GetMicroBlockTransactionsCountByHashParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMicroBlockTransactionsCountByHashParamsWithTimeout(timeout time.Duration) *GetMicroBlockTransactionsCountByHashParams {
	var ()
	return &GetMicroBlockTransactionsCountByHashParams{

		timeout: timeout,
	}
}

// NewGetMicroBlockTransactionsCountByHashParamsWithContext creates a new GetMicroBlockTransactionsCountByHashParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMicroBlockTransactionsCountByHashParamsWithContext(ctx context.Context) *GetMicroBlockTransactionsCountByHashParams {
	var ()
	return &GetMicroBlockTransactionsCountByHashParams{

		Context: ctx,
	}
}

// NewGetMicroBlockTransactionsCountByHashParamsWithHTTPClient creates a new GetMicroBlockTransactionsCountByHashParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMicroBlockTransactionsCountByHashParamsWithHTTPClient(client *http.Client) *GetMicroBlockTransactionsCountByHashParams {
	var ()
	return &GetMicroBlockTransactionsCountByHashParams{
		HTTPClient: client,
	}
}

/*GetMicroBlockTransactionsCountByHashParams contains all the parameters to send to the API endpoint
for the get micro block transactions count by hash operation typically these are written to a http.Request
*/
type GetMicroBlockTransactionsCountByHashParams struct {

	/*Hash
	  The hash of the block

	*/
	Hash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) WithTimeout(timeout time.Duration) *GetMicroBlockTransactionsCountByHashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) WithContext(ctx context.Context) *GetMicroBlockTransactionsCountByHashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) WithHTTPClient(client *http.Client) *GetMicroBlockTransactionsCountByHashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHash adds the hash to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) WithHash(hash string) *GetMicroBlockTransactionsCountByHashParams {
	o.SetHash(hash)
	return o
}

// SetHash adds the hash to the get micro block transactions count by hash params
func (o *GetMicroBlockTransactionsCountByHashParams) SetHash(hash string) {
	o.Hash = hash
}

// WriteToRequest writes these params to a swagger request
func (o *GetMicroBlockTransactionsCountByHashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hash
	if err := r.SetPathParam("hash", o.Hash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
