// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlockLatestParams creates a new GetBlockLatestParams object
// with the default values initialized.
func NewGetBlockLatestParams() *GetBlockLatestParams {
	var (
		txEncodingDefault = string("json")
	)
	return &GetBlockLatestParams{
		TxEncoding: &txEncodingDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlockLatestParamsWithTimeout creates a new GetBlockLatestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBlockLatestParamsWithTimeout(timeout time.Duration) *GetBlockLatestParams {
	var (
		txEncodingDefault = string("json")
	)
	return &GetBlockLatestParams{
		TxEncoding: &txEncodingDefault,

		timeout: timeout,
	}
}

// NewGetBlockLatestParamsWithContext creates a new GetBlockLatestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBlockLatestParamsWithContext(ctx context.Context) *GetBlockLatestParams {
	var (
		txEncodingDefault = string("json")
	)
	return &GetBlockLatestParams{
		TxEncoding: &txEncodingDefault,

		Context: ctx,
	}
}

// NewGetBlockLatestParamsWithHTTPClient creates a new GetBlockLatestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBlockLatestParamsWithHTTPClient(client *http.Client) *GetBlockLatestParams {
	var (
		txEncodingDefault = string("json")
	)
	return &GetBlockLatestParams{
		TxEncoding: &txEncodingDefault,
		HTTPClient: client,
	}
}

/*GetBlockLatestParams contains all the parameters to send to the API endpoint
for the get block latest operation typically these are written to a http.Request
*/
type GetBlockLatestParams struct {

	/*TxEncoding
	  Transactions encoding

	*/
	TxEncoding *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get block latest params
func (o *GetBlockLatestParams) WithTimeout(timeout time.Duration) *GetBlockLatestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get block latest params
func (o *GetBlockLatestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get block latest params
func (o *GetBlockLatestParams) WithContext(ctx context.Context) *GetBlockLatestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get block latest params
func (o *GetBlockLatestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get block latest params
func (o *GetBlockLatestParams) WithHTTPClient(client *http.Client) *GetBlockLatestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get block latest params
func (o *GetBlockLatestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTxEncoding adds the txEncoding to the get block latest params
func (o *GetBlockLatestParams) WithTxEncoding(txEncoding *string) *GetBlockLatestParams {
	o.SetTxEncoding(txEncoding)
	return o
}

// SetTxEncoding adds the txEncoding to the get block latest params
func (o *GetBlockLatestParams) SetTxEncoding(txEncoding *string) {
	o.TxEncoding = txEncoding
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlockLatestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TxEncoding != nil {

		// query param tx_encoding
		var qrTxEncoding string
		if o.TxEncoding != nil {
			qrTxEncoding = *o.TxEncoding
		}
		qTxEncoding := qrTxEncoding
		if qTxEncoding != "" {
			if err := r.SetQueryParam("tx_encoding", qTxEncoding); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
