// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrentKeyBlockHashParams creates a new GetCurrentKeyBlockHashParams object
// with the default values initialized.
func NewGetCurrentKeyBlockHashParams() *GetCurrentKeyBlockHashParams {

	return &GetCurrentKeyBlockHashParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentKeyBlockHashParamsWithTimeout creates a new GetCurrentKeyBlockHashParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentKeyBlockHashParamsWithTimeout(timeout time.Duration) *GetCurrentKeyBlockHashParams {

	return &GetCurrentKeyBlockHashParams{

		timeout: timeout,
	}
}

// NewGetCurrentKeyBlockHashParamsWithContext creates a new GetCurrentKeyBlockHashParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentKeyBlockHashParamsWithContext(ctx context.Context) *GetCurrentKeyBlockHashParams {

	return &GetCurrentKeyBlockHashParams{

		Context: ctx,
	}
}

// NewGetCurrentKeyBlockHashParamsWithHTTPClient creates a new GetCurrentKeyBlockHashParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCurrentKeyBlockHashParamsWithHTTPClient(client *http.Client) *GetCurrentKeyBlockHashParams {

	return &GetCurrentKeyBlockHashParams{
		HTTPClient: client,
	}
}

/*GetCurrentKeyBlockHashParams contains all the parameters to send to the API endpoint
for the get current key block hash operation typically these are written to a http.Request
*/
type GetCurrentKeyBlockHashParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) WithTimeout(timeout time.Duration) *GetCurrentKeyBlockHashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) WithContext(ctx context.Context) *GetCurrentKeyBlockHashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) WithHTTPClient(client *http.Client) *GetCurrentKeyBlockHashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current key block hash params
func (o *GetCurrentKeyBlockHashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentKeyBlockHashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
