// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// GetCurrentKeyBlockHashReader is a Reader for the GetCurrentKeyBlockHash structure.
type GetCurrentKeyBlockHashReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentKeyBlockHashReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCurrentKeyBlockHashOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCurrentKeyBlockHashOK creates a GetCurrentKeyBlockHashOK with default headers values
func NewGetCurrentKeyBlockHashOK() *GetCurrentKeyBlockHashOK {
	return &GetCurrentKeyBlockHashOK{}
}

/*GetCurrentKeyBlockHashOK handles this case with default header values.

Successful operation
*/
type GetCurrentKeyBlockHashOK struct {
	Payload *models.InlineResponse200
}

func (o *GetCurrentKeyBlockHashOK) Error() string {
	return fmt.Sprintf("[GET /key-blocks/current/hash][%d] getCurrentKeyBlockHashOK  %+v", 200, o.Payload)
}

func (o *GetCurrentKeyBlockHashOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
