// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// GetLatestBlockTxsCountReader is a Reader for the GetLatestBlockTxsCount structure.
type GetLatestBlockTxsCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLatestBlockTxsCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLatestBlockTxsCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLatestBlockTxsCountOK creates a GetLatestBlockTxsCountOK with default headers values
func NewGetLatestBlockTxsCountOK() *GetLatestBlockTxsCountOK {
	return &GetLatestBlockTxsCountOK{}
}

/*GetLatestBlockTxsCountOK handles this case with default header values.

The count of transactions in the latest block
*/
type GetLatestBlockTxsCountOK struct {
	Payload *models.InlineResponse2003
}

func (o *GetLatestBlockTxsCountOK) Error() string {
	return fmt.Sprintf("[GET /block/txs/count/latest][%d] getLatestBlockTxsCountOK  %+v", 200, o.Payload)
}

func (o *GetLatestBlockTxsCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse2003)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
