// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// GetPeersReader is a Reader for the GetPeers structure.
type GetPeersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPeersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPeersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetPeersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPeersOK creates a GetPeersOK with default headers values
func NewGetPeersOK() *GetPeersOK {
	return &GetPeersOK{}
}

/*GetPeersOK handles this case with default header values.

successful operation
*/
type GetPeersOK struct {
	Payload *models.Peers
}

func (o *GetPeersOK) Error() string {
	return fmt.Sprintf("[GET /debug/peers][%d] getPeersOK  %+v", 200, o.Payload)
}

func (o *GetPeersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Peers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPeersForbidden creates a GetPeersForbidden with default headers values
func NewGetPeersForbidden() *GetPeersForbidden {
	return &GetPeersForbidden{}
}

/*GetPeersForbidden handles this case with default header values.

Info not enabled
*/
type GetPeersForbidden struct {
	Payload *models.Error
}

func (o *GetPeersForbidden) Error() string {
	return fmt.Sprintf("[GET /debug/peers][%d] getPeersForbidden  %+v", 403, o.Payload)
}

func (o *GetPeersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
