// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// GetBlockLatestReader is a Reader for the GetBlockLatest structure.
type GetBlockLatestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBlockLatestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBlockLatestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBlockLatestOK creates a GetBlockLatestOK with default headers values
func NewGetBlockLatestOK() *GetBlockLatestOK {
	return &GetBlockLatestOK{}
}

/*GetBlockLatestOK handles this case with default header values.

The top block
*/
type GetBlockLatestOK struct {
	Payload *models.GenericBlock
}

func (o *GetBlockLatestOK) Error() string {
	return fmt.Sprintf("[GET /block/latest][%d] getBlockLatestOK  %+v", 200, o.Payload)
}

func (o *GetBlockLatestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericBlock)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
