// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNameParams creates a new GetNameParams object
// with the default values initialized.
func NewGetNameParams() *GetNameParams {
	var ()
	return &GetNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNameParamsWithTimeout creates a new GetNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNameParamsWithTimeout(timeout time.Duration) *GetNameParams {
	var ()
	return &GetNameParams{

		timeout: timeout,
	}
}

// NewGetNameParamsWithContext creates a new GetNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNameParamsWithContext(ctx context.Context) *GetNameParams {
	var ()
	return &GetNameParams{

		Context: ctx,
	}
}

// NewGetNameParamsWithHTTPClient creates a new GetNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNameParamsWithHTTPClient(client *http.Client) *GetNameParams {
	var ()
	return &GetNameParams{
		HTTPClient: client,
	}
}

/*GetNameParams contains all the parameters to send to the API endpoint
for the get name operation typically these are written to a http.Request
*/
type GetNameParams struct {

	/*Name
	  Name to get entry from Naming System

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get name params
func (o *GetNameParams) WithTimeout(timeout time.Duration) *GetNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get name params
func (o *GetNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get name params
func (o *GetNameParams) WithContext(ctx context.Context) *GetNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get name params
func (o *GetNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get name params
func (o *GetNameParams) WithHTTPClient(client *http.Client) *GetNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get name params
func (o *GetNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get name params
func (o *GetNameParams) WithName(name string) *GetNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get name params
func (o *GetNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
