// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// PostNameTransferTxReader is a Reader for the PostNameTransferTx structure.
type PostNameTransferTxReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostNameTransferTxReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostNameTransferTxOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostNameTransferTxBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostNameTransferTxNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostNameTransferTxOK creates a PostNameTransferTxOK with default headers values
func NewPostNameTransferTxOK() *PostNameTransferTxOK {
	return &PostNameTransferTxOK{}
}

/*PostNameTransferTxOK handles this case with default header values.

successful operation
*/
type PostNameTransferTxOK struct {
	Payload *models.NameHash
}

func (o *PostNameTransferTxOK) Error() string {
	return fmt.Sprintf("[POST /name-transfer-tx][%d] postNameTransferTxOK  %+v", 200, o.Payload)
}

func (o *PostNameTransferTxOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NameHash)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostNameTransferTxBadRequest creates a PostNameTransferTxBadRequest with default headers values
func NewPostNameTransferTxBadRequest() *PostNameTransferTxBadRequest {
	return &PostNameTransferTxBadRequest{}
}

/*PostNameTransferTxBadRequest handles this case with default header values.

Name transfer transaction validation error
*/
type PostNameTransferTxBadRequest struct {
	Payload *models.Error
}

func (o *PostNameTransferTxBadRequest) Error() string {
	return fmt.Sprintf("[POST /name-transfer-tx][%d] postNameTransferTxBadRequest  %+v", 400, o.Payload)
}

func (o *PostNameTransferTxBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostNameTransferTxNotFound creates a PostNameTransferTxNotFound with default headers values
func NewPostNameTransferTxNotFound() *PostNameTransferTxNotFound {
	return &PostNameTransferTxNotFound{}
}

/*PostNameTransferTxNotFound handles this case with default header values.

Account not found error
*/
type PostNameTransferTxNotFound struct {
	Payload *models.Error
}

func (o *PostNameTransferTxNotFound) Error() string {
	return fmt.Sprintf("[POST /name-transfer-tx][%d] postNameTransferTxNotFound  %+v", 404, o.Payload)
}

func (o *PostNameTransferTxNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
