// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// PostContractCreateReader is a Reader for the PostContractCreate structure.
type PostContractCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostContractCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostContractCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostContractCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostContractCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostContractCreateOK creates a PostContractCreateOK with default headers values
func NewPostContractCreateOK() *PostContractCreateOK {
	return &PostContractCreateOK{}
}

/*PostContractCreateOK handles this case with default header values.

Successful operation
*/
type PostContractCreateOK struct {
	Payload *models.CreateContractUnsignedTx
}

func (o *PostContractCreateOK) Error() string {
	return fmt.Sprintf("[POST /tx/contract/create][%d] postContractCreateOK  %+v", 200, o.Payload)
}

func (o *PostContractCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateContractUnsignedTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostContractCreateBadRequest creates a PostContractCreateBadRequest with default headers values
func NewPostContractCreateBadRequest() *PostContractCreateBadRequest {
	return &PostContractCreateBadRequest{}
}

/*PostContractCreateBadRequest handles this case with default header values.

Invalid transaction
*/
type PostContractCreateBadRequest struct {
	Payload *models.Error
}

func (o *PostContractCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /tx/contract/create][%d] postContractCreateBadRequest  %+v", 400, o.Payload)
}

func (o *PostContractCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostContractCreateNotFound creates a PostContractCreateNotFound with default headers values
func NewPostContractCreateNotFound() *PostContractCreateNotFound {
	return &PostContractCreateNotFound{}
}

/*PostContractCreateNotFound handles this case with default header values.

Owner account not found
*/
type PostContractCreateNotFound struct {
	Payload *models.Error
}

func (o *PostContractCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /tx/contract/create][%d] postContractCreateNotFound  %+v", 404, o.Payload)
}

func (o *PostContractCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
