// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostContractCallComputeParams creates a new PostContractCallComputeParams object
// with the default values initialized.
func NewPostContractCallComputeParams() *PostContractCallComputeParams {
	var ()
	return &PostContractCallComputeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostContractCallComputeParamsWithTimeout creates a new PostContractCallComputeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostContractCallComputeParamsWithTimeout(timeout time.Duration) *PostContractCallComputeParams {
	var ()
	return &PostContractCallComputeParams{

		timeout: timeout,
	}
}

// NewPostContractCallComputeParamsWithContext creates a new PostContractCallComputeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostContractCallComputeParamsWithContext(ctx context.Context) *PostContractCallComputeParams {
	var ()
	return &PostContractCallComputeParams{

		Context: ctx,
	}
}

// NewPostContractCallComputeParamsWithHTTPClient creates a new PostContractCallComputeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostContractCallComputeParamsWithHTTPClient(client *http.Client) *PostContractCallComputeParams {
	var ()
	return &PostContractCallComputeParams{
		HTTPClient: client,
	}
}

/*PostContractCallComputeParams contains all the parameters to send to the API endpoint
for the post contract call compute operation typically these are written to a http.Request
*/
type PostContractCallComputeParams struct {

	/*Body*/
	Body *models.ContractCallCompute

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post contract call compute params
func (o *PostContractCallComputeParams) WithTimeout(timeout time.Duration) *PostContractCallComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post contract call compute params
func (o *PostContractCallComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post contract call compute params
func (o *PostContractCallComputeParams) WithContext(ctx context.Context) *PostContractCallComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post contract call compute params
func (o *PostContractCallComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post contract call compute params
func (o *PostContractCallComputeParams) WithHTTPClient(client *http.Client) *PostContractCallComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post contract call compute params
func (o *PostContractCallComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post contract call compute params
func (o *PostContractCallComputeParams) WithBody(body *models.ContractCallCompute) *PostContractCallComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post contract call compute params
func (o *PostContractCallComputeParams) SetBody(body *models.ContractCallCompute) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostContractCallComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
