// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostNamePreclaimParams creates a new PostNamePreclaimParams object
// with the default values initialized.
func NewPostNamePreclaimParams() *PostNamePreclaimParams {
	var ()
	return &PostNamePreclaimParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostNamePreclaimParamsWithTimeout creates a new PostNamePreclaimParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostNamePreclaimParamsWithTimeout(timeout time.Duration) *PostNamePreclaimParams {
	var ()
	return &PostNamePreclaimParams{

		timeout: timeout,
	}
}

// NewPostNamePreclaimParamsWithContext creates a new PostNamePreclaimParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostNamePreclaimParamsWithContext(ctx context.Context) *PostNamePreclaimParams {
	var ()
	return &PostNamePreclaimParams{

		Context: ctx,
	}
}

// NewPostNamePreclaimParamsWithHTTPClient creates a new PostNamePreclaimParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostNamePreclaimParamsWithHTTPClient(client *http.Client) *PostNamePreclaimParams {
	var ()
	return &PostNamePreclaimParams{
		HTTPClient: client,
	}
}

/*PostNamePreclaimParams contains all the parameters to send to the API endpoint
for the post name preclaim operation typically these are written to a http.Request
*/
type PostNamePreclaimParams struct {

	/*Body*/
	Body *models.NamePreclaimTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post name preclaim params
func (o *PostNamePreclaimParams) WithTimeout(timeout time.Duration) *PostNamePreclaimParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post name preclaim params
func (o *PostNamePreclaimParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post name preclaim params
func (o *PostNamePreclaimParams) WithContext(ctx context.Context) *PostNamePreclaimParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post name preclaim params
func (o *PostNamePreclaimParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post name preclaim params
func (o *PostNamePreclaimParams) WithHTTPClient(client *http.Client) *PostNamePreclaimParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post name preclaim params
func (o *PostNamePreclaimParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post name preclaim params
func (o *PostNamePreclaimParams) WithBody(body *models.NamePreclaimTx) *PostNamePreclaimParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post name preclaim params
func (o *PostNamePreclaimParams) SetBody(body *models.NamePreclaimTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostNamePreclaimParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
