// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostChannelWithdrawalParams creates a new PostChannelWithdrawalParams object
// with the default values initialized.
func NewPostChannelWithdrawalParams() *PostChannelWithdrawalParams {
	var ()
	return &PostChannelWithdrawalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChannelWithdrawalParamsWithTimeout creates a new PostChannelWithdrawalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChannelWithdrawalParamsWithTimeout(timeout time.Duration) *PostChannelWithdrawalParams {
	var ()
	return &PostChannelWithdrawalParams{

		timeout: timeout,
	}
}

// NewPostChannelWithdrawalParamsWithContext creates a new PostChannelWithdrawalParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChannelWithdrawalParamsWithContext(ctx context.Context) *PostChannelWithdrawalParams {
	var ()
	return &PostChannelWithdrawalParams{

		Context: ctx,
	}
}

// NewPostChannelWithdrawalParamsWithHTTPClient creates a new PostChannelWithdrawalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChannelWithdrawalParamsWithHTTPClient(client *http.Client) *PostChannelWithdrawalParams {
	var ()
	return &PostChannelWithdrawalParams{
		HTTPClient: client,
	}
}

/*PostChannelWithdrawalParams contains all the parameters to send to the API endpoint
for the post channel withdrawal operation typically these are written to a http.Request
*/
type PostChannelWithdrawalParams struct {

	/*Body*/
	Body *models.ChannelWithdrawalTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) WithTimeout(timeout time.Duration) *PostChannelWithdrawalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) WithContext(ctx context.Context) *PostChannelWithdrawalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) WithHTTPClient(client *http.Client) *PostChannelWithdrawalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) WithBody(body *models.ChannelWithdrawalTx) *PostChannelWithdrawalParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post channel withdrawal params
func (o *PostChannelWithdrawalParams) SetBody(body *models.ChannelWithdrawalTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostChannelWithdrawalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
