// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostChannelCloseMutualParams creates a new PostChannelCloseMutualParams object
// with the default values initialized.
func NewPostChannelCloseMutualParams() *PostChannelCloseMutualParams {
	var ()
	return &PostChannelCloseMutualParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChannelCloseMutualParamsWithTimeout creates a new PostChannelCloseMutualParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChannelCloseMutualParamsWithTimeout(timeout time.Duration) *PostChannelCloseMutualParams {
	var ()
	return &PostChannelCloseMutualParams{

		timeout: timeout,
	}
}

// NewPostChannelCloseMutualParamsWithContext creates a new PostChannelCloseMutualParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChannelCloseMutualParamsWithContext(ctx context.Context) *PostChannelCloseMutualParams {
	var ()
	return &PostChannelCloseMutualParams{

		Context: ctx,
	}
}

// NewPostChannelCloseMutualParamsWithHTTPClient creates a new PostChannelCloseMutualParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChannelCloseMutualParamsWithHTTPClient(client *http.Client) *PostChannelCloseMutualParams {
	var ()
	return &PostChannelCloseMutualParams{
		HTTPClient: client,
	}
}

/*PostChannelCloseMutualParams contains all the parameters to send to the API endpoint
for the post channel close mutual operation typically these are written to a http.Request
*/
type PostChannelCloseMutualParams struct {

	/*Body*/
	Body *models.ChannelCloseMutualTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post channel close mutual params
func (o *PostChannelCloseMutualParams) WithTimeout(timeout time.Duration) *PostChannelCloseMutualParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post channel close mutual params
func (o *PostChannelCloseMutualParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post channel close mutual params
func (o *PostChannelCloseMutualParams) WithContext(ctx context.Context) *PostChannelCloseMutualParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post channel close mutual params
func (o *PostChannelCloseMutualParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post channel close mutual params
func (o *PostChannelCloseMutualParams) WithHTTPClient(client *http.Client) *PostChannelCloseMutualParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post channel close mutual params
func (o *PostChannelCloseMutualParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post channel close mutual params
func (o *PostChannelCloseMutualParams) WithBody(body *models.ChannelCloseMutualTx) *PostChannelCloseMutualParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post channel close mutual params
func (o *PostChannelCloseMutualParams) SetBody(body *models.ChannelCloseMutualTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostChannelCloseMutualParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
