// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostContractCreateParams creates a new PostContractCreateParams object
// with the default values initialized.
func NewPostContractCreateParams() *PostContractCreateParams {
	var ()
	return &PostContractCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostContractCreateParamsWithTimeout creates a new PostContractCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostContractCreateParamsWithTimeout(timeout time.Duration) *PostContractCreateParams {
	var ()
	return &PostContractCreateParams{

		timeout: timeout,
	}
}

// NewPostContractCreateParamsWithContext creates a new PostContractCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostContractCreateParamsWithContext(ctx context.Context) *PostContractCreateParams {
	var ()
	return &PostContractCreateParams{

		Context: ctx,
	}
}

// NewPostContractCreateParamsWithHTTPClient creates a new PostContractCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostContractCreateParamsWithHTTPClient(client *http.Client) *PostContractCreateParams {
	var ()
	return &PostContractCreateParams{
		HTTPClient: client,
	}
}

/*PostContractCreateParams contains all the parameters to send to the API endpoint
for the post contract create operation typically these are written to a http.Request
*/
type PostContractCreateParams struct {

	/*Body*/
	Body *models.ContractCreateData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post contract create params
func (o *PostContractCreateParams) WithTimeout(timeout time.Duration) *PostContractCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post contract create params
func (o *PostContractCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post contract create params
func (o *PostContractCreateParams) WithContext(ctx context.Context) *PostContractCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post contract create params
func (o *PostContractCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post contract create params
func (o *PostContractCreateParams) WithHTTPClient(client *http.Client) *PostContractCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post contract create params
func (o *PostContractCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post contract create params
func (o *PostContractCreateParams) WithBody(body *models.ContractCreateData) *PostContractCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post contract create params
func (o *PostContractCreateParams) SetBody(body *models.ContractCreateData) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostContractCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
