// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// PostContractCallComputeReader is a Reader for the PostContractCallCompute structure.
type PostContractCallComputeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostContractCallComputeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostContractCallComputeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostContractCallComputeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostContractCallComputeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostContractCallComputeOK creates a PostContractCallComputeOK with default headers values
func NewPostContractCallComputeOK() *PostContractCallComputeOK {
	return &PostContractCallComputeOK{}
}

/*PostContractCallComputeOK handles this case with default header values.

Successful operation
*/
type PostContractCallComputeOK struct {
	Payload *models.UnsignedTx
}

func (o *PostContractCallComputeOK) Error() string {
	return fmt.Sprintf("[POST /tx/contract/call/compute][%d] postContractCallComputeOK  %+v", 200, o.Payload)
}

func (o *PostContractCallComputeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnsignedTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostContractCallComputeBadRequest creates a PostContractCallComputeBadRequest with default headers values
func NewPostContractCallComputeBadRequest() *PostContractCallComputeBadRequest {
	return &PostContractCallComputeBadRequest{}
}

/*PostContractCallComputeBadRequest handles this case with default header values.

Invalid transaction
*/
type PostContractCallComputeBadRequest struct {
	Payload *models.Error
}

func (o *PostContractCallComputeBadRequest) Error() string {
	return fmt.Sprintf("[POST /tx/contract/call/compute][%d] postContractCallComputeBadRequest  %+v", 400, o.Payload)
}

func (o *PostContractCallComputeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostContractCallComputeNotFound creates a PostContractCallComputeNotFound with default headers values
func NewPostContractCallComputeNotFound() *PostContractCallComputeNotFound {
	return &PostContractCallComputeNotFound{}
}

/*PostContractCallComputeNotFound handles this case with default header values.

Caller account or contract not found
*/
type PostContractCallComputeNotFound struct {
	Payload *models.Error
}

func (o *PostContractCallComputeNotFound) Error() string {
	return fmt.Sprintf("[POST /tx/contract/call/compute][%d] postContractCallComputeNotFound  %+v", 404, o.Payload)
}

func (o *PostContractCallComputeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
