// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// PostChannelCreateReader is a Reader for the PostChannelCreate structure.
type PostChannelCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChannelCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostChannelCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostChannelCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostChannelCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostChannelCreateOK creates a PostChannelCreateOK with default headers values
func NewPostChannelCreateOK() *PostChannelCreateOK {
	return &PostChannelCreateOK{}
}

/*PostChannelCreateOK handles this case with default header values.

Successful operation
*/
type PostChannelCreateOK struct {
	Payload *models.UnsignedTx
}

func (o *PostChannelCreateOK) Error() string {
	return fmt.Sprintf("[POST /tx/channel/create][%d] postChannelCreateOK  %+v", 200, o.Payload)
}

func (o *PostChannelCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnsignedTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChannelCreateBadRequest creates a PostChannelCreateBadRequest with default headers values
func NewPostChannelCreateBadRequest() *PostChannelCreateBadRequest {
	return &PostChannelCreateBadRequest{}
}

/*PostChannelCreateBadRequest handles this case with default header values.

Invalid transaction
*/
type PostChannelCreateBadRequest struct {
	Payload *models.Error
}

func (o *PostChannelCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /tx/channel/create][%d] postChannelCreateBadRequest  %+v", 400, o.Payload)
}

func (o *PostChannelCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChannelCreateNotFound creates a PostChannelCreateNotFound with default headers values
func NewPostChannelCreateNotFound() *PostChannelCreateNotFound {
	return &PostChannelCreateNotFound{}
}

/*PostChannelCreateNotFound handles this case with default header values.

Initiator not found
*/
type PostChannelCreateNotFound struct {
	Payload *models.Error
}

func (o *PostChannelCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /tx/channel/create][%d] postChannelCreateNotFound  %+v", 404, o.Payload)
}

func (o *PostChannelCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
