// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostChannelSettleParams creates a new PostChannelSettleParams object
// with the default values initialized.
func NewPostChannelSettleParams() *PostChannelSettleParams {
	var ()
	return &PostChannelSettleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChannelSettleParamsWithTimeout creates a new PostChannelSettleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChannelSettleParamsWithTimeout(timeout time.Duration) *PostChannelSettleParams {
	var ()
	return &PostChannelSettleParams{

		timeout: timeout,
	}
}

// NewPostChannelSettleParamsWithContext creates a new PostChannelSettleParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChannelSettleParamsWithContext(ctx context.Context) *PostChannelSettleParams {
	var ()
	return &PostChannelSettleParams{

		Context: ctx,
	}
}

// NewPostChannelSettleParamsWithHTTPClient creates a new PostChannelSettleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChannelSettleParamsWithHTTPClient(client *http.Client) *PostChannelSettleParams {
	var ()
	return &PostChannelSettleParams{
		HTTPClient: client,
	}
}

/*PostChannelSettleParams contains all the parameters to send to the API endpoint
for the post channel settle operation typically these are written to a http.Request
*/
type PostChannelSettleParams struct {

	/*Body*/
	Body *models.ChannelSettleTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post channel settle params
func (o *PostChannelSettleParams) WithTimeout(timeout time.Duration) *PostChannelSettleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post channel settle params
func (o *PostChannelSettleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post channel settle params
func (o *PostChannelSettleParams) WithContext(ctx context.Context) *PostChannelSettleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post channel settle params
func (o *PostChannelSettleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post channel settle params
func (o *PostChannelSettleParams) WithHTTPClient(client *http.Client) *PostChannelSettleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post channel settle params
func (o *PostChannelSettleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post channel settle params
func (o *PostChannelSettleParams) WithBody(body *models.ChannelSettleTx) *PostChannelSettleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post channel settle params
func (o *PostChannelSettleParams) SetBody(body *models.ChannelSettleTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostChannelSettleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
