// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostChannelSLASHParams creates a new PostChannelSLASHParams object
// with the default values initialized.
func NewPostChannelSLASHParams() *PostChannelSLASHParams {
	var ()
	return &PostChannelSLASHParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChannelSLASHParamsWithTimeout creates a new PostChannelSLASHParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChannelSLASHParamsWithTimeout(timeout time.Duration) *PostChannelSLASHParams {
	var ()
	return &PostChannelSLASHParams{

		timeout: timeout,
	}
}

// NewPostChannelSLASHParamsWithContext creates a new PostChannelSLASHParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChannelSLASHParamsWithContext(ctx context.Context) *PostChannelSLASHParams {
	var ()
	return &PostChannelSLASHParams{

		Context: ctx,
	}
}

// NewPostChannelSLASHParamsWithHTTPClient creates a new PostChannelSLASHParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChannelSLASHParamsWithHTTPClient(client *http.Client) *PostChannelSLASHParams {
	var ()
	return &PostChannelSLASHParams{
		HTTPClient: client,
	}
}

/*PostChannelSLASHParams contains all the parameters to send to the API endpoint
for the post channel slash operation typically these are written to a http.Request
*/
type PostChannelSLASHParams struct {

	/*Body*/
	Body *models.ChannelSLASHTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post channel slash params
func (o *PostChannelSLASHParams) WithTimeout(timeout time.Duration) *PostChannelSLASHParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post channel slash params
func (o *PostChannelSLASHParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post channel slash params
func (o *PostChannelSLASHParams) WithContext(ctx context.Context) *PostChannelSLASHParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post channel slash params
func (o *PostChannelSLASHParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post channel slash params
func (o *PostChannelSLASHParams) WithHTTPClient(client *http.Client) *PostChannelSLASHParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post channel slash params
func (o *PostChannelSLASHParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post channel slash params
func (o *PostChannelSLASHParams) WithBody(body *models.ChannelSLASHTx) *PostChannelSLASHParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post channel slash params
func (o *PostChannelSLASHParams) SetBody(body *models.ChannelSLASHTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostChannelSLASHParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
