// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// NewPostNameUpdateParams creates a new PostNameUpdateParams object
// with the default values initialized.
func NewPostNameUpdateParams() *PostNameUpdateParams {
	var ()
	return &PostNameUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostNameUpdateParamsWithTimeout creates a new PostNameUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostNameUpdateParamsWithTimeout(timeout time.Duration) *PostNameUpdateParams {
	var ()
	return &PostNameUpdateParams{

		timeout: timeout,
	}
}

// NewPostNameUpdateParamsWithContext creates a new PostNameUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostNameUpdateParamsWithContext(ctx context.Context) *PostNameUpdateParams {
	var ()
	return &PostNameUpdateParams{

		Context: ctx,
	}
}

// NewPostNameUpdateParamsWithHTTPClient creates a new PostNameUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostNameUpdateParamsWithHTTPClient(client *http.Client) *PostNameUpdateParams {
	var ()
	return &PostNameUpdateParams{
		HTTPClient: client,
	}
}

/*PostNameUpdateParams contains all the parameters to send to the API endpoint
for the post name update operation typically these are written to a http.Request
*/
type PostNameUpdateParams struct {

	/*Body*/
	Body *models.NameUpdateTx

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post name update params
func (o *PostNameUpdateParams) WithTimeout(timeout time.Duration) *PostNameUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post name update params
func (o *PostNameUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post name update params
func (o *PostNameUpdateParams) WithContext(ctx context.Context) *PostNameUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post name update params
func (o *PostNameUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post name update params
func (o *PostNameUpdateParams) WithHTTPClient(client *http.Client) *PostNameUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post name update params
func (o *PostNameUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post name update params
func (o *PostNameUpdateParams) WithBody(body *models.NameUpdateTx) *PostNameUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post name update params
func (o *PostNameUpdateParams) SetBody(body *models.NameUpdateTx) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostNameUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
