// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aeternity/aepp-sdk-go/models"
)

// PostChannelWithdrawalReader is a Reader for the PostChannelWithdrawal structure.
type PostChannelWithdrawalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChannelWithdrawalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostChannelWithdrawalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostChannelWithdrawalBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostChannelWithdrawalOK creates a PostChannelWithdrawalOK with default headers values
func NewPostChannelWithdrawalOK() *PostChannelWithdrawalOK {
	return &PostChannelWithdrawalOK{}
}

/*PostChannelWithdrawalOK handles this case with default header values.

Successful operation
*/
type PostChannelWithdrawalOK struct {
	Payload *models.UnsignedTx
}

func (o *PostChannelWithdrawalOK) Error() string {
	return fmt.Sprintf("[POST /tx/channel/withdrawal][%d] postChannelWithdrawalOK  %+v", 200, o.Payload)
}

func (o *PostChannelWithdrawalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnsignedTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChannelWithdrawalBadRequest creates a PostChannelWithdrawalBadRequest with default headers values
func NewPostChannelWithdrawalBadRequest() *PostChannelWithdrawalBadRequest {
	return &PostChannelWithdrawalBadRequest{}
}

/*PostChannelWithdrawalBadRequest handles this case with default header values.

Invalid transaction
*/
type PostChannelWithdrawalBadRequest struct {
	Payload *models.Error
}

func (o *PostChannelWithdrawalBadRequest) Error() string {
	return fmt.Sprintf("[POST /tx/channel/withdrawal][%d] postChannelWithdrawalBadRequest  %+v", 400, o.Payload)
}

func (o *PostChannelWithdrawalBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
