name: Test, build, and release
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        make lint

    - run: make test-unit
    - run: docker-compose up -d
    - name: Ensure that node is running
      run: |
        while [[ `curl -s -o /dev/null -w %{http_code} localhost:3013/api` != 200 ]]; do
          sleep 0.2;
        done
    - run: make test-integration

    - name: Build
      if: true != startsWith(github.ref, 'refs/tags/')
      run: make build-release

    - name: Build release
      if: startsWith(github.ref, 'refs/tags/')
      run: make build-release

    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/windows.zip
          dist/darwin.zip
          dist/linux.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
