// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AccountsBalances accounts balances
// swagger:model AccountsBalances
type AccountsBalances struct {

	// accounts balances
	AccountsBalances []*AccountBalance `json:"accounts_balances"`
}

// Validate validates this accounts balances
func (m *AccountsBalances) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountsBalances(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountsBalances) validateAccountsBalances(formats strfmt.Registry) error {

	if swag.IsZero(m.AccountsBalances) { // not required
		return nil
	}

	for i := 0; i < len(m.AccountsBalances); i++ {
		if swag.IsZero(m.AccountsBalances[i]) { // not required
			continue
		}

		if m.AccountsBalances[i] != nil {
			if err := m.AccountsBalances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accounts_balances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountsBalances) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountsBalances) UnmarshalBinary(b []byte) error {
	var res AccountsBalances
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
