// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ChannelWithdrawalTxJSON channel withdrawal tx JSON
// swagger:model ChannelWithdrawalTxJSON
type ChannelWithdrawalTxJSON struct {
	vsnField int64

	ChannelWithdrawalTx
}

// DataSchema gets the data schema of this subtype
func (m *ChannelWithdrawalTxJSON) DataSchema() string {
	return "ChannelWithdrawalTxJSON"
}

// SetDataSchema sets the data schema of this subtype
func (m *ChannelWithdrawalTxJSON) SetDataSchema(val string) {

}

// Vsn gets the vsn of this subtype
func (m *ChannelWithdrawalTxJSON) Vsn() int64 {
	return m.vsnField
}

// SetVsn sets the vsn of this subtype
func (m *ChannelWithdrawalTxJSON) SetVsn(val int64) {
	m.vsnField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *ChannelWithdrawalTxJSON) UnmarshalJSON(raw []byte) error {
	var data struct {
		ChannelWithdrawalTx
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		DataSchema string `json:"data_schema"`

		Vsn int64 `json:"vsn,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result ChannelWithdrawalTxJSON

	if base.DataSchema != result.DataSchema() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid data_schema value: %q", base.DataSchema)
	}

	result.vsnField = base.Vsn

	result.ChannelWithdrawalTx = data.ChannelWithdrawalTx

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m ChannelWithdrawalTxJSON) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		ChannelWithdrawalTx
	}{

		ChannelWithdrawalTx: m.ChannelWithdrawalTx,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		DataSchema string `json:"data_schema"`

		Vsn int64 `json:"vsn,omitempty"`
	}{

		DataSchema: m.DataSchema(),

		Vsn: m.Vsn(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this channel withdrawal tx JSON
func (m *ChannelWithdrawalTxJSON) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ChannelWithdrawalTx
	if err := m.ChannelWithdrawalTx.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelWithdrawalTxJSON) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelWithdrawalTxJSON) UnmarshalBinary(b []byte) error {
	var res ChannelWithdrawalTxJSON
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
