// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OracleQueryTx oracle query tx
// swagger:model OracleQueryTx
type OracleQueryTx struct {

	// fee
	// Required: true
	Fee *int64 `json:"fee"`

	// Sender nonce
	Nonce int64 `json:"nonce,omitempty"`

	// oracle pubkey
	// Required: true
	OraclePubkey *string `json:"oracle_pubkey"`

	// query
	// Required: true
	Query *string `json:"query"`

	// query fee
	// Required: true
	QueryFee *int64 `json:"query_fee"`

	// query ttl
	// Required: true
	QueryTTL *TTL `json:"query_ttl"`

	// response ttl
	// Required: true
	ResponseTTL *RelativeTTL `json:"response_ttl"`

	// sender
	Sender EncodedHash `json:"sender,omitempty"`

	// ttl
	TTL int64 `json:"ttl,omitempty"`
}

// Validate validates this oracle query tx
func (m *OracleQueryTx) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOraclePubkey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuery(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueryFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueryTTL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResponseTTL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSender(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OracleQueryTx) validateFee(formats strfmt.Registry) error {

	if err := validate.Required("fee", "body", m.Fee); err != nil {
		return err
	}

	return nil
}

func (m *OracleQueryTx) validateOraclePubkey(formats strfmt.Registry) error {

	if err := validate.Required("oracle_pubkey", "body", m.OraclePubkey); err != nil {
		return err
	}

	return nil
}

func (m *OracleQueryTx) validateQuery(formats strfmt.Registry) error {

	if err := validate.Required("query", "body", m.Query); err != nil {
		return err
	}

	return nil
}

func (m *OracleQueryTx) validateQueryFee(formats strfmt.Registry) error {

	if err := validate.Required("query_fee", "body", m.QueryFee); err != nil {
		return err
	}

	return nil
}

func (m *OracleQueryTx) validateQueryTTL(formats strfmt.Registry) error {

	if err := validate.Required("query_ttl", "body", m.QueryTTL); err != nil {
		return err
	}

	if m.QueryTTL != nil {
		if err := m.QueryTTL.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("query_ttl")
			}
			return err
		}
	}

	return nil
}

func (m *OracleQueryTx) validateResponseTTL(formats strfmt.Registry) error {

	if err := validate.Required("response_ttl", "body", m.ResponseTTL); err != nil {
		return err
	}

	if m.ResponseTTL != nil {
		if err := m.ResponseTTL.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("response_ttl")
			}
			return err
		}
	}

	return nil
}

func (m *OracleQueryTx) validateSender(formats strfmt.Registry) error {

	if swag.IsZero(m.Sender) { // not required
		return nil
	}

	if err := m.Sender.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("sender")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OracleQueryTx) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OracleQueryTx) UnmarshalBinary(b []byte) error {
	var res OracleQueryTx
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
