// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OracleRegisterTx oracle register tx
// swagger:model OracleRegisterTx
type OracleRegisterTx struct {

	// account
	Account EncodedHash `json:"account,omitempty"`

	// fee
	// Required: true
	Fee *int64 `json:"fee"`

	// nonce
	Nonce int64 `json:"nonce,omitempty"`

	// oracle ttl
	// Required: true
	OracleTTL *TTL `json:"oracle_ttl"`

	// query fee
	// Required: true
	QueryFee *int64 `json:"query_fee"`

	// query format
	// Required: true
	QueryFormat *string `json:"query_format"`

	// response format
	// Required: true
	ResponseFormat *string `json:"response_format"`

	// ttl
	TTL int64 `json:"ttl,omitempty"`
}

// Validate validates this oracle register tx
func (m *OracleRegisterTx) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOracleTTL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueryFee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueryFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResponseFormat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OracleRegisterTx) validateAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.Account) { // not required
		return nil
	}

	if err := m.Account.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("account")
		}
		return err
	}

	return nil
}

func (m *OracleRegisterTx) validateFee(formats strfmt.Registry) error {

	if err := validate.Required("fee", "body", m.Fee); err != nil {
		return err
	}

	return nil
}

func (m *OracleRegisterTx) validateOracleTTL(formats strfmt.Registry) error {

	if err := validate.Required("oracle_ttl", "body", m.OracleTTL); err != nil {
		return err
	}

	if m.OracleTTL != nil {
		if err := m.OracleTTL.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("oracle_ttl")
			}
			return err
		}
	}

	return nil
}

func (m *OracleRegisterTx) validateQueryFee(formats strfmt.Registry) error {

	if err := validate.Required("query_fee", "body", m.QueryFee); err != nil {
		return err
	}

	return nil
}

func (m *OracleRegisterTx) validateQueryFormat(formats strfmt.Registry) error {

	if err := validate.Required("query_format", "body", m.QueryFormat); err != nil {
		return err
	}

	return nil
}

func (m *OracleRegisterTx) validateResponseFormat(formats strfmt.Registry) error {

	if err := validate.Required("response_format", "body", m.ResponseFormat); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OracleRegisterTx) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OracleRegisterTx) UnmarshalBinary(b []byte) error {
	var res OracleRegisterTx
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
