// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RegisteredOraclesInner registered oracles inner
// swagger:model RegisteredOracles_inner
type RegisteredOraclesInner struct {

	// address
	Address string `json:"address,omitempty"`

	// expires at
	ExpiresAt int64 `json:"expires_at,omitempty"`

	// query fee
	QueryFee int64 `json:"query_fee,omitempty"`

	// query format
	QueryFormat string `json:"query_format,omitempty"`

	// response format
	ResponseFormat string `json:"response_format,omitempty"`
}

// Validate validates this registered oracles inner
func (m *RegisteredOraclesInner) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisteredOraclesInner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisteredOraclesInner) UnmarshalBinary(b []byte) error {
	var res RegisteredOraclesInner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
