// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SophiaBinaryData sophia binary data
// swagger:model SophiaBinaryData
type SophiaBinaryData struct {

	// data
	// Required: true
	Data *string `json:"data"`

	// sophia type
	// Required: true
	SophiaType *string `json:"sophia-type"`
}

// Validate validates this sophia binary data
func (m *SophiaBinaryData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSophiaType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SophiaBinaryData) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

func (m *SophiaBinaryData) validateSophiaType(formats strfmt.Registry) error {

	if err := validate.Required("sophia-type", "body", m.SophiaType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SophiaBinaryData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SophiaBinaryData) UnmarshalBinary(b []byte) error {
	var res SophiaBinaryData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
